- api/dhcp/v1alpha2/dhcpsubnet_types.go
- api/dhcp/v1alpha2/groupversion_info.go
- api/wiring/v1alpha2/meta.go
- api/wiring/v1alpha2/rack_types.go
- config/crd/bases/dhcp.githedgehog.com_dhcpsubnets.yaml
- config/crd/bases/wiring.githedgehog.com_racks.yaml
- docs/api.md
> typos: few proof readings and grep

- pkg/dhcpd/dhcphandlers.go
> pxe + http fix 

- api/meta/types.go
- api/wiring/v1alpha2/connection_types.go
- api/wiring/v1alpha2/connection_types_test.go
> Allow default route for StaticExternal

- pkg/agent/dozer/bcm/spec_comm_lists.go
- pkg/agent/dozer/bcm/spec_comm_lists_test.go
> [agent] dedup comm lists members

- pkg/webhook/connection/connection_webhook.go
This patch was attached to a fork that I deleted. We use branches here.
> check for MCLAG connections before deleting MCLAG domain

- pkg/agent/dozer/bcm/plan.go
> Fix mixed leaf ext routes redist

- pkg/agent/agent.go
> Enforce switch state every 2 mins

- api/wiring/v1beta1/switch_types.go
> Fix switch roles list and check

- cmd/hhfctl/main.go
- pkg/hhfctl/inspect/bgp.go
- pkg/hhfctl/inspect/inspect.go
- pkg/hhfctl/inspect/lldp.go
- pkg/util/apiutil/lldp.go
- ignore mgmt port when inspecting lldp
- print all errors and output for strict mode
> Improve inspect commands

- pkg/hhfctl/vpc.go
* use DeleteAllOf instead of deleting objects one by one
* expose a call with the kube client as a param, which is useful in release tests in fabricator (where we want to reuse a pre-existing client)
> minor tweaks to hhfctl vpc wipe

- pkg/agent/dozer/bcm/plan.go
> Fix port auto neg handling to avoid unappliable diff

- pkg/agent/dozer/bcm/spec_interface.go
> Avoid sending both autoNeg and portSpeed at the same time

- docs/profiles.md
- pkg/ctrl/switchprofile/catalog.go
- pkg/ctrl/switchprofile/profile_celestica_ds4101.go
> Add Celestica DS4101 profile

- pkg/hhfctl/inspect/bgp.go
- pkg/hhfctl/inspect/lldp.go
- pkg/util/apiutil/bgp.go
- pkg/util/apiutil/lldp.go
> feat: support gateway conns in inspect lldp/bgp

- pkg/agent/agent.go
Currently it's never triggered b/c heartbeat timer is always happening first and enforce timer is just being reset.
Fixes #796
> fix: trigger periodic enforcer on ticker

- pkg/agent/agent.go
> fix: rework heartbeats and periodic reinforcements for reliability

- api/wiring/v1beta1/switchprofile_types.go
- docs/profiles.md
- docs/supported-devices.md
- pkg/ctrl/switchprofile/catalog.go
- pkg/ctrl/switchprofile/profile_celestica_ds5000.go
- pkg/ctrl/switchprofile/silicons.go
fixes https://github.com/githedgehog/internal/issues/117
> Switch profile for ds50000

- pkg/agent/dozer/bcm/plan.go
- pkg/agent/dozer/bcm/spec_lst.go
- pkg/agent/dozer/dozer.go
> feat: enable mclag link state tracking

- cmd/hhfctl/main.go
- pkg/hhfctl/switch.go
> feat(ctl): allow to run command over ssh

- api/dhcp/v1beta1/dhcpsubnet_types.go
- api/vpc/v1beta1/vpc_types.go
- cmd/hhfctl/main.go
- config/crd/bases/agent.githedgehog.com_agents.yaml
- config/crd/bases/dhcp.githedgehog.com_dhcpsubnets.yaml
- config/crd/bases/vpc.githedgehog.com_vpcs.yaml
- docs/api.md
- pkg/ctrl/vpc_ctrl.go
- pkg/dhcpd/dhcphandlers.go
- pkg/dhcpd/dhcphandlers_test.go
- pkg/dhcpd/types.go
> feat: expose dhcp lease time config

- pkg/agent/dozer/bcm/spec_prefix_lists.go
Same issue as with route maps.
Fixes #893
> fix(agent,bcm-450): avoid replacing prefixlist base

- pkg/util/apiutil/lldp.go
Currently the invalid logic is that we've been caching by switch profile but that means that if different switches with the same profile have different breakouts configured we will cache mapping that is only valid for one switch but not the others (with the same profile).
Fixes #413
> fix(inspect): cache NOS2API port mapping per switch name instead profile

- pkg/agent/agent.go
- pkg/agent/dozer/bcm/plan.go
> fix(agent): breakout should only be skipped if roce is actually enabled

- pkg/agent/dozer/bcm/enforcer.go
- pkg/agent/dozer/bcm/plan.go
- pkg/agent/dozer/bcm/spec.go
- pkg/agent/dozer/bcm/spec_bfd.go
- pkg/agent/dozer/bcm/spec_vrf.go
- pkg/agent/dozer/dozer.go
> feat(agent): add bfd support and enable it for fabric links

- pkg/agent/dozer/bcm/plan.go
- pkg/ctrl/agent_ctrl.go
for static externals not bound to a VPC, we were adding their subnets to a prefix list in the attached leaf and allowing them to be advertised. However those routes will die at the spines unless we also allow advertisment there. To do that, we must pass the static external connection info to spines too (if they are global) and populate prefix lists there as well.
> fix(agent): global staticExternal route adv

- .github/workflows/ci.yaml
- pkg/agent/dozer/bcm/plan.go
- pkg/hhfctl/inspect/ip.go
- pkg/util/apiutil/bgp.go
- pkg/util/apiutil/lldp.go
to replace collapsed core.
Fix #973
> mesh connection types

- pkg/agent/dozer/bcm/enforcer.go
- pkg/agent/dozer/bcm/spec_vrf.go
Related githedgehog/internal#223
> fix: agent is unable to remove filter-attached-hosts route-map

- .github/workflows/ci.yaml
> ci: add vlab upgrade testing

- pkg/agent/dozer/bcm/plan.go
> chore: remove VTEP subnet fallback

- pkg/agent/dozer/bcm/processor.go
Related githedgehog/fabricator#927
> feat(agent): ignore if only tpcm isn't ready

- api/wiring/v1beta1/switchprofile_types.go
- config/crd/bases/agent.githedgehog.com_agents.yaml
- config/crd/bases/wiring.githedgehog.com_switchprofiles.yaml
- docs/api.md
> chore: remove deprecated vxlan from profiles

- pkg/webhook/connection/connection_webhook.go
> chore: immutable WithinVPC for static ext
